"""creation des 14 entites metier

Revision ID: 0ecd676d66b6
Revises: 
Create Date: 2026-09-05 11:00:45.497665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ecd676d66b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('siege', 'client', name='type_site'), nullable=False),
    sa.Column('adresse', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_site_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_site_modifie_par_id_utilisateur'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site'))
    )
    op.create_table('equipement',
    sa.Column('identity', sa.String(length=40), nullable=False),
    sa.Column('marque', sa.Enum('MikroTik', 'Grandstream', 'Ubiquiti', 'Ruijie', 'autre', name='marque_equipement'), nullable=False),
    sa.Column('modele', sa.String(length=60), nullable=False),
    sa.Column('numero_serie', sa.String(length=60), nullable=False),
    sa.Column('adresse_mac', sa.String(length=17), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('emplacement', sa.String(length=120), nullable=False),
    sa.Column('date_installation', sa.Date(), nullable=False),
    sa.Column('fin_garantie', sa.Date(), nullable=True),
    sa.Column('statut', sa.Enum('en_service', 'en_panne', 'en_maintenance', 'retire', name='statut_equipement'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_equipement_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_equipement_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_equipement_site_id_site')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipement')),
    sa.UniqueConstraint('identity', name=op.f('uq_equipement_identity')),
    sa.UniqueConstraint('numero_serie', name=op.f('uq_equipement_numero_serie'))
    )
    op.create_table('utilisateur',
    sa.Column('nom', sa.String(length=60), nullable=False),
    sa.Column('prenom', sa.String(length=60), nullable=False),
    sa.Column('identifiant', sa.String(length=40), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('administrateur', 'referent_sheq', 'responsable', 'technicien', 'collaborateur', name='role_utilisateur'), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('courriel', sa.String(length=120), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_utilisateur_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_utilisateur_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_utilisateur_site_id_site')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utilisateur')),
    sa.UniqueConstraint('identifiant', name=op.f('uq_utilisateur_identifiant'))
    )
    op.create_table('configuration',
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('equipement_id', sa.Integer(), nullable=False),
    sa.Column('type_intervention', sa.Enum('installation', 'reconfiguration', 'mise_a_jour', 'depannage', 'alignement', name='type_intervention'), nullable=False),
    sa.Column('version_logicielle', sa.String(length=40), nullable=True),
    sa.Column('parametres_reseau', sa.JSON(), nullable=True),
    sa.Column('parametres_sansfil', sa.JSON(), nullable=True),
    sa.Column('signal_dbm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('ccq_pourcent', sa.Integer(), nullable=True),
    sa.Column('tests_realises', sa.JSON(), nullable=True),
    sa.Column('fichiers_sauvegarde', sa.JSON(), nullable=True),
    sa.Column('technicien_id', sa.Integer(), nullable=False),
    sa.Column('date_intervention', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_configuration_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['equipement_id'], ['equipement.id'], name=op.f('fk_configuration_equipement_id_equipement')),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_configuration_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['technicien_id'], ['utilisateur.id'], name=op.f('fk_configuration_technicien_id_utilisateur')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration')),
    sa.UniqueConstraint('reference', name=op.f('uq_configuration_reference'))
    )
    op.create_table('document',
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('intitule', sa.String(length=200), nullable=False),
    sa.Column('niveau', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('redacteur_id', sa.Integer(), nullable=False),
    sa.Column('approbateur_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('brouillon', 'en_approbation', 'en_vigueur', 'archive', name='statut_document'), nullable=False),
    sa.Column('date_revue', sa.Date(), nullable=True),
    sa.Column('confidentialite', sa.Enum('normal', 'confidentiel', name='confidentialite_document'), nullable=False),
    sa.Column('fichier', sa.String(length=255), nullable=True),
    sa.Column('accuses_lecture', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('niveau BETWEEN 1 AND 4', name=op.f('ck_document_ck_document_niveau_1_4')),
    sa.ForeignKeyConstraint(['approbateur_id'], ['utilisateur.id'], name=op.f('fk_document_approbateur_id_utilisateur')),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_document_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_document_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['redacteur_id'], ['utilisateur.id'], name=op.f('fk_document_redacteur_id_utilisateur')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document')),
    sa.UniqueConstraint('reference', name=op.f('uq_document_reference'))
    )
    op.create_table('epi',
    sa.Column('numero', sa.String(length=12), nullable=False),
    sa.Column('type', sa.Enum('harnais', 'longe', 'antichute_mobile', 'casque', 'connecteur', 'ligne_de_vie', name='type_epi'), nullable=False),
    sa.Column('marque_modele', sa.String(length=80), nullable=False),
    sa.Column('date_fabrication', sa.Date(), nullable=True),
    sa.Column('date_mise_service', sa.Date(), nullable=False),
    sa.Column('date_limite', sa.Date(), nullable=False),
    sa.Column('porteur_id', sa.Integer(), nullable=True),
    sa.Column('derniere_verification', sa.Date(), nullable=True),
    sa.Column('prochaine_verification', sa.Date(), nullable=True),
    sa.Column('statut', sa.Enum('en_service', 'a_verifier', 'retire', 'reforme', name='statut_epi'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_epi_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_epi_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['porteur_id'], ['utilisateur.id'], name=op.f('fk_epi_porteur_id_utilisateur')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_epi')),
    sa.UniqueConstraint('numero', name=op.f('uq_epi_numero'))
    )
    op.create_table('evaluation_slam',
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('etapes_validees', sa.JSON(), nullable=False),
    sa.Column('decision', sa.Enum('GO', 'NO_GO', name='decision_slam'), nullable=False),
    sa.Column('motif', sa.String(length=300), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_evaluation_slam_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_evaluation_slam_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_evaluation_slam_utilisateur_id_utilisateur')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_slam'))
    )
    op.create_table('inspection',
    sa.Column('modele', sa.Enum('locaux', 'incendie', 'electricite', 'installations', 'equipements', name='type_inspection'), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('inspecteur_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('taux_conformite', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('statut', sa.Enum('en_cours', 'cloturee', name='statut_inspection'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_inspection_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['inspecteur_id'], ['utilisateur.id'], name=op.f('fk_inspection_inspecteur_id_utilisateur')),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_inspection_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_inspection_site_id_site')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection'))
    )
    op.create_table('permis',
    sa.Column('reference', sa.String(length=16), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('nature_travaux', sa.String(length=200), nullable=False),
    sa.Column('support', sa.Enum('pylone', 'toiture', 'echelle', 'autre', name='support_permis'), nullable=False),
    sa.Column('hauteur_estimee', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('surveillant_id', sa.Integer(), nullable=False),
    sa.Column('debut_validite', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin_validite', sa.DateTime(timezone=True), nullable=False),
    sa.Column('controles', sa.JSON(), nullable=True),
    sa.Column('statut', sa.Enum('demande', 'bloque', 'delivre', 'cloture', 'refuse', name='statut_permis'), nullable=False),
    sa.Column('validateur_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_permis_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_permis_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_permis_site_id_site')),
    sa.ForeignKeyConstraint(['surveillant_id'], ['utilisateur.id'], name=op.f('fk_permis_surveillant_id_utilisateur')),
    sa.ForeignKeyConstraint(['validateur_id'], ['utilisateur.id'], name=op.f('fk_permis_validateur_id_utilisateur')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permis')),
    sa.UniqueConstraint('reference', name=op.f('uq_permis_reference'))
    )
    op.create_table('risque',
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('danger', sa.String(length=200), nullable=False),
    sa.Column('categorie', sa.Enum('Ergonomique', 'Électrique', 'Incendie', 'Chute / Circulation', 'Psychosocial (RPS)', 'Manutention', 'Ambiances physiques', 'Hygiène / Biologique', "Sécurité de l'information", 'Sécurité / Sûreté', 'Routier / Trajet', 'Incendie / Urgences', name='categorie_risque'), nullable=False),
    sa.Column('unite_travail', sa.String(length=80), nullable=False),
    sa.Column('personnes_exposees', sa.String(length=120), nullable=True),
    sa.Column('mesures_existantes', sa.Text(), nullable=True),
    sa.Column('probabilite', sa.Integer(), nullable=False),
    sa.Column('gravite', sa.Integer(), nullable=False),
    sa.Column('criticite', sa.Integer(), nullable=False),
    sa.Column('niveau', sa.Enum('faible', 'modéré', 'élevé', 'critique', name='niveau_risque'), nullable=False),
    sa.Column('mesures_proposees', sa.Text(), nullable=False),
    sa.Column('date_evaluation', sa.Date(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('gravite BETWEEN 1 AND 5', name=op.f('ck_risque_ck_risque_gravite_1_5')),
    sa.CheckConstraint('probabilite BETWEEN 1 AND 5', name=op.f('ck_risque_ck_risque_probabilite_1_5')),
    sa.ForeignKeyConstraint(['auteur_id'], ['utilisateur.id'], name=op.f('fk_risque_auteur_id_utilisateur')),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_risque_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_risque_modifie_par_id_utilisateur'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risque'))
    )
    op.create_table('secret',
    sa.Column('libelle', sa.String(length=120), nullable=False),
    sa.Column('equipement_id', sa.Integer(), nullable=True),
    sa.Column('type_acces', sa.Enum('administration', 'cle_reseau', 'compte_cloud', 'autre', name='type_acces'), nullable=False),
    sa.Column('identifiant', sa.String(length=80), nullable=True),
    sa.Column('valeur_chiffree', sa.LargeBinary(), nullable=False),
    sa.Column('role_requis', sa.Enum('administrateur', 'referent_sheq', 'responsable', 'technicien', 'collaborateur', name='role_requis_secret'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_secret_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['equipement_id'], ['equipement.id'], name=op.f('fk_secret_equipement_id_equipement')),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_secret_modifie_par_id_utilisateur'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secret'))
    )
    op.create_table('journal_acces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('secret_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('horodatage', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.Enum('consultation', 'creation', 'modification', name='action_journal'), nullable=False),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_journal_acces_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['secret_id'], ['secret.id'], name=op.f('fk_journal_acces_secret_id_secret')),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_journal_acces_utilisateur_id_utilisateur')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_acces'))
    )
    op.create_table('permis_intervenants',
    sa.Column('permis_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permis_id'], ['permis.id'], name=op.f('fk_permis_intervenants_permis_id_permis')),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_permis_intervenants_utilisateur_id_utilisateur')),
    sa.PrimaryKeyConstraint('permis_id', 'utilisateur_id', name=op.f('pk_permis_intervenants'))
    )
    op.create_table('signalement',
    sa.Column('reference', sa.String(length=20), nullable=True),
    sa.Column('type', sa.Enum('situation_dangereuse', 'presque_accident', 'anomalie', 'incident', 'accident', name='type_signalement'), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('lieu', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('anonyme', sa.Boolean(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.Column('date_constat', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_saisie', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_synchro', sa.DateTime(timezone=True), nullable=True),
    sa.Column('causes', sa.Text(), nullable=True),
    sa.Column('risque_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('nouveau', 'en_analyse', 'actions_definies', 'cloture', name='statut_signalement'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['utilisateur.id'], name=op.f('fk_signalement_auteur_id_utilisateur')),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_signalement_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_signalement_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['risque_id'], ['risque.id'], name=op.f('fk_signalement_risque_id_risque')),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_signalement_site_id_site')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signalement')),
    sa.UniqueConstraint('reference', name=op.f('uq_signalement_reference'))
    )
    op.create_table('action',
    sa.Column('libelle', sa.String(length=200), nullable=False),
    sa.Column('risque_id', sa.Integer(), nullable=True),
    sa.Column('signalement_id', sa.Integer(), nullable=True),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('type_mesure', sa.Enum('corrective', 'preventive', 'amelioration', name='type_mesure_action'), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('echeance', sa.Date(), nullable=False),
    sa.Column('avancement', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('ouverte', 'en_cours', 'cloturee', name='statut_action'), nullable=False),
    sa.Column('indicateur', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('avancement BETWEEN 0 AND 100', name=op.f('ck_action_ck_action_avancement_0_100')),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_action_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], name=op.f('fk_action_inspection_id_inspection')),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_action_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['responsable_id'], ['utilisateur.id'], name=op.f('fk_action_responsable_id_utilisateur')),
    sa.ForeignKeyConstraint(['risque_id'], ['risque.id'], name=op.f('fk_action_risque_id_risque')),
    sa.ForeignKeyConstraint(['signalement_id'], ['signalement.id'], name=op.f('fk_action_signalement_id_signalement')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action')
    op.drop_table('signalement')
    op.drop_table('permis_intervenants')
    op.drop_table('journal_acces')
    op.drop_table('secret')
    op.drop_table('risque')
    op.drop_table('permis')
    op.drop_table('inspection')
    op.drop_table('evaluation_slam')
    op.drop_table('epi')
    op.drop_table('document')
    op.drop_table('configuration')
    op.drop_table('utilisateur')
    op.drop_table('equipement')
    op.drop_table('site')
    # ### end Alembic commands ###
