"""protection brute-force connexion

Revision ID: 129412013be2
Revises: f4181e7fcfe3
Create Date: 2026-09-08 05:30:19.168866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129412013be2'
down_revision: Union[str, Sequence[str], None] = 'f4181e7fcfe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default nécessaire (pas seulement le default=0 côté modèle) :
    # sans lui, ADD COLUMN NOT NULL échoue sur une table qui a déjà des
    # lignes (utilisateurs existants) — aussi bien sous SQLite que PostgreSQL.
    op.add_column(
        'utilisateur', sa.Column('tentatives_echouees', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column('utilisateur', sa.Column('verrouille_jusqua', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'verrouille_jusqua')
    op.drop_column('utilisateur', 'tentatives_echouees')
    # ### end Alembic commands ###
