"""objet_inspecte sur inspection

Revision ID: 3197fb535115
Revises: 129412013be2
Create Date: 2026-09-10 03:11:40.667234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3197fb535115'
down_revision: Union[str, Sequence[str], None] = '129412013be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Objet précis inspecté (extincteur, tableau électrique, ligne de vie…)
    quand ce n'est pas un équipement du parc — retour utilisateur 2026-09-10.
    Nullable, aucun server_default : les inspections existantes restent sans
    objet renseigné, ce qui est le comportement voulu."""
    op.add_column('inspection', sa.Column('objet_inspecte', sa.String(length=200), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspection', 'objet_inspecte')
    # ### end Alembic commands ###
