"""photo de profil utilisateur

Revision ID: 5b9a3eb3a30b
Revises: 7901cba3e6ab
Create Date: 2026-09-10 11:30:38.336276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9a3eb3a30b'
down_revision: Union[str, Sequence[str], None] = '7901cba3e6ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('photo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'photo')
    # ### end Alembic commands ###
