"""socle assistance ia (appel_assistance, type_notification plafond)

Revision ID: 64e0ce301864
Revises: 8c5e991840c5
Create Date: 2026-09-07 02:38:44.554634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e0ce301864'
down_revision: Union[str, Sequence[str], None] = '8c5e991840c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # PLAFOND_ASSISTANCE ajoutée à TypeNotification (prompt 6.1, alerte
    # administrateur du chapitre 16.4) : aucune migration de schéma requise.
    # `enum_column()` (app/db/base.py) construit un `sa.Enum` sans
    # `create_constraint=True` — en SQLAlchemy 2.x, `create_constraint` vaut
    # `False` par défaut pour un type non natif comme celui de SQLite, donc
    # la colonne `notification.type` est un simple VARCHAR sans contrainte
    # CHECK (vérifié directement sur le schéma réel : `sqlite_master` ne
    # montre aucun `CHECK` sur cette colonne). La validation des valeurs
    # d'énumération se fait uniquement côté Python (Pydantic/SQLAlchemy ORM),
    # jamais en base — ajouter une valeur à l'énumération Python ne modifie
    # donc rien de ce que SQLite impose.

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appel_assistance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('fonction', sa.String(length=60), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('volume_caracteres', sa.Integer(), nullable=False),
    sa.Column('duree_ms', sa.Integer(), nullable=False),
    sa.Column('cout_estime_usd', sa.Float(), nullable=True),
    sa.Column('succes', sa.Boolean(), nullable=False),
    sa.Column('horodatage', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_appel_assistance_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_appel_assistance_utilisateur_id_utilisateur')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appel_assistance'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appel_assistance')
    # ### end Alembic commands ###
