"""documents visiteurs dechets et satisfaction client

Revision ID: 6efa01e166a2
Revises: d2b3c4e5f6a7
Create Date: 2026-09-06 10:20:30.796019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6efa01e166a2'
down_revision: Union[str, Sequence[str], None] = 'd2b3c4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visiteur',
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('societe', sa.String(length=120), nullable=True),
    sa.Column('motif', sa.String(length=200), nullable=False),
    sa.Column('personne_visitee', sa.String(length=120), nullable=True),
    sa.Column('heure_arrivee', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heure_depart', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consignes_lues', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_visiteur_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_visiteur_modifie_par_id_utilisateur'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visiteur'))
    )
    op.create_table('dechet',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantite', sa.String(length=60), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('filiere', sa.String(length=120), nullable=False),
    sa.Column('date_enlevement', sa.Date(), nullable=True),
    sa.Column('justificatif', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_dechet_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_dechet_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_dechet_site_id_site')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dechet'))
    )
    op.create_table('enquete_satisfaction',
    sa.Column('jeton', sa.String(length=40), nullable=False),
    sa.Column('client', sa.String(length=120), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('intervention', sa.String(length=200), nullable=False),
    sa.Column('technicien_id', sa.Integer(), nullable=True),
    sa.Column('envoyee_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('repondu', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_enquete_satisfaction_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_enquete_satisfaction_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_enquete_satisfaction_site_id_site')),
    sa.ForeignKeyConstraint(['technicien_id'], ['utilisateur.id'], name=op.f('fk_enquete_satisfaction_technicien_id_utilisateur')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enquete_satisfaction')),
    sa.UniqueConstraint('jeton', name=op.f('uq_enquete_satisfaction_jeton'))
    )
    op.create_table('reponse_satisfaction',
    sa.Column('enquete_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('recommandation', sa.Enum('oui_certainement', 'probablement', 'non', name='recommandation'), nullable=False),
    sa.Column('remarques', sa.Text(), nullable=True),
    sa.Column('necessite_analyse', sa.Boolean(), nullable=False),
    sa.Column('date_reponse', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_reponse_satisfaction_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['enquete_id'], ['enquete_satisfaction.id'], name=op.f('fk_reponse_satisfaction_enquete_id_enquete_satisfaction')),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_reponse_satisfaction_modifie_par_id_utilisateur'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reponse_satisfaction'))
    )
    # batch_alter_table : SQLite ne supporte pas l'ajout d'une contrainte de
    # clé étrangère nommée ni le remplacement d'une contrainte UNIQUE via
    # ALTER TABLE (même motif que 14382e24e575, b0fef0f9add6).
    with op.batch_alter_table("action") as batch_op:
        batch_op.add_column(sa.Column('reponse_satisfaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            op.f('fk_action_reponse_satisfaction_id_reponse_satisfaction'),
            'reponse_satisfaction',
            ['reponse_satisfaction_id'],
            ['id'],
        )
    with op.batch_alter_table("document") as batch_op:
        batch_op.drop_constraint(op.f('uq_document_reference'), type_='unique')
        batch_op.create_unique_constraint('uq_document_reference_version', ['reference', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document") as batch_op:
        batch_op.drop_constraint('uq_document_reference_version', type_='unique')
        batch_op.create_unique_constraint(op.f('uq_document_reference'), ['reference'])
    with op.batch_alter_table("action") as batch_op:
        batch_op.drop_constraint(
            op.f('fk_action_reponse_satisfaction_id_reponse_satisfaction'), type_='foreignkey'
        )
        batch_op.drop_column('reponse_satisfaction_id')
    op.drop_table('reponse_satisfaction')
    op.drop_table('enquete_satisfaction')
    op.drop_table('dechet')
    op.drop_table('visiteur')
    # ### end Alembic commands ###
