"""historisation des cotations de risque

Revision ID: 88a3ec5c2f5f
Revises: 14382e24e575
Create Date: 2026-09-06 08:47:08.590723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a3ec5c2f5f'
down_revision: Union[str, Sequence[str], None] = '14382e24e575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotation_risque',
    sa.Column('risque_id', sa.Integer(), nullable=False),
    sa.Column('mesures_existantes', sa.Text(), nullable=True),
    sa.Column('probabilite', sa.Integer(), nullable=False),
    sa.Column('gravite', sa.Integer(), nullable=False),
    sa.Column('criticite', sa.Integer(), nullable=False),
    sa.Column('niveau', sa.Enum('faible', 'modéré', 'élevé', 'critique', name='niveau_risque'), nullable=False),
    sa.Column('mesures_proposees', sa.Text(), nullable=False),
    sa.Column('date_evaluation', sa.Date(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('gravite BETWEEN 1 AND 5', name=op.f('ck_cotation_risque_gravite_1_5')),
    sa.CheckConstraint('probabilite BETWEEN 1 AND 5', name=op.f('ck_cotation_risque_probabilite_1_5')),
    sa.ForeignKeyConstraint(['auteur_id'], ['utilisateur.id'], name=op.f('fk_cotation_risque_auteur_id_utilisateur')),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_cotation_risque_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_cotation_risque_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['risque_id'], ['risque.id'], name=op.f('fk_cotation_risque_risque_id_risque')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cotation_risque'))
    )
    # batch_alter_table : SQLite ne supporte pas DROP COLUMN / DROP CONSTRAINT
    # directement (même motif que 4b398dde2947, fb8c539876c8, 14382e24e575) —
    # le mode batch reconstruit la table à partir des métadonnées actuelles du
    # modèle, ce qui élimine aussi proprement les anciennes contraintes CHECK
    # liées à probabilite/gravite (non détectées explicitement par
    # l'autogénération, mais devenues sans objet une fois ces colonnes retirées).
    with op.batch_alter_table("risque") as batch_op:
        batch_op.create_unique_constraint(op.f("uq_risque_numero"), ["numero"])
        batch_op.drop_constraint(op.f("fk_risque_auteur_id_utilisateur"), type_="foreignkey")
        # Contraintes CHECK historiques (nommées avec le doublon de préfixe du
        # bug préexistant, voir app/models/cotation_risque.py) : sans ce drop
        # explicite, le mode batch les reporterait telles quelles sur la
        # nouvelle table alors qu'elles référencent des colonnes sur le point
        # d'être supprimées, ce qui échoue à la reconstruction ("no such
        # column: gravite").
        batch_op.drop_constraint(op.f("ck_risque_ck_risque_gravite_1_5"), type_="check")
        batch_op.drop_constraint(op.f("ck_risque_ck_risque_probabilite_1_5"), type_="check")
        batch_op.drop_column("gravite")
        batch_op.drop_column("niveau")
        batch_op.drop_column("mesures_existantes")
        batch_op.drop_column("auteur_id")
        batch_op.drop_column("probabilite")
        batch_op.drop_column("criticite")
        batch_op.drop_column("date_evaluation")
        batch_op.drop_column("mesures_proposees")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table("risque") as batch_op:
        batch_op.add_column(sa.Column("mesures_proposees", sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column("date_evaluation", sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column("criticite", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("probabilite", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("auteur_id", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("mesures_existantes", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("niveau", sa.VARCHAR(length=8), nullable=False))
        batch_op.add_column(sa.Column("gravite", sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(
            op.f("fk_risque_auteur_id_utilisateur"), "utilisateur", ["auteur_id"], ["id"]
        )
        batch_op.create_check_constraint(op.f("ck_risque_ck_risque_gravite_1_5"), "gravite BETWEEN 1 AND 5")
        batch_op.create_check_constraint(
            op.f("ck_risque_ck_risque_probabilite_1_5"), "probabilite BETWEEN 1 AND 5"
        )
        batch_op.drop_constraint(op.f("uq_risque_numero"), type_="unique")
    op.drop_table('cotation_risque')
    # ### end Alembic commands ###
