"""notifications

Revision ID: 90df54758db3
Revises: 6efa01e166a2
Create Date: 2026-09-06 10:58:05.251341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90df54758db3'
down_revision: Union[str, Sequence[str], None] = '6efa01e166a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('destinataire_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('nouveau_signalement', 'permis_en_attente', 'decision_no_go', 'action_echeance', 'epi_verification', 'inspection_planifiee', 'satisfaction_faible', 'document_revue', name='type_notification'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('objet_type', sa.String(length=30), nullable=True),
    sa.Column('objet_id', sa.Integer(), nullable=True),
    sa.Column('declencheur', sa.String(length=10), nullable=True),
    sa.Column('canal', sa.Enum('application', 'courriel', 'les_deux', name='canal_notification'), nullable=False),
    sa.Column('lue', sa.Boolean(), nullable=False),
    sa.Column('lue_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('courriel_envoye', sa.Boolean(), nullable=True),
    sa.Column('courriel_erreur', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_notification_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['destinataire_id'], ['utilisateur.id'], name=op.f('fk_notification_destinataire_id_utilisateur')),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_notification_modifie_par_id_utilisateur'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification')),
    sa.UniqueConstraint('type', 'objet_type', 'objet_id', 'destinataire_id', 'declencheur', name='uq_notification_deduplication')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
