"""ajout motif_reforme sur epi

Revision ID: 99cb17e1c898
Revises: 0ecd676d66b6
Create Date: 2026-09-05 14:47:52.588726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99cb17e1c898'
down_revision: Union[str, Sequence[str], None] = '0ecd676d66b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epi', sa.Column('motif_reforme', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('epi', 'motif_reforme')
    # ### end Alembic commands ###
