"""formations audits et revues de direction

Revision ID: b0fef0f9add6
Revises: 88a3ec5c2f5f
Create Date: 2026-09-06 09:37:30.798936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0fef0f9add6'
down_revision: Union[str, Sequence[str], None] = '88a3ec5c2f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competence',
    sa.Column('libelle', sa.String(length=120), nullable=False),
    sa.Column('periodicite_mois', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_competence_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_competence_modifie_par_id_utilisateur'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competence'))
    )
    op.create_table('exigence_audit',
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('chapitre', sa.String(length=60), nullable=False),
    sa.Column('libelle', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_exigence_audit_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_exigence_audit_modifie_par_id_utilisateur'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exigence_audit')),
    sa.UniqueConstraint('numero', name=op.f('uq_exigence_audit_numero'))
    )
    op.create_table('question_quiz',
    sa.Column('enonce', sa.Text(), nullable=False),
    sa.Column('choix', sa.JSON(), nullable=False),
    sa.Column('reponse_correcte', sa.String(length=1), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_question_quiz_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_question_quiz_modifie_par_id_utilisateur'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_quiz'))
    )
    op.create_table('campagne_audit',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('auditeur_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('en_cours', 'cloturee', name='statut_inspection'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auditeur_id'], ['utilisateur.id'], name=op.f('fk_campagne_audit_auditeur_id_utilisateur')),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_campagne_audit_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_campagne_audit_modifie_par_id_utilisateur'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campagne_audit'))
    )
    op.create_table('habilitation',
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=False),
    sa.Column('date_obtention', sa.Date(), nullable=False),
    sa.Column('date_expiration', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competence_id'], ['competence.id'], name=op.f('fk_habilitation_competence_id_competence')),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_habilitation_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_habilitation_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_habilitation_utilisateur_id_utilisateur')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habilitation'))
    )
    op.create_table('revue_direction',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lieu', sa.String(length=120), nullable=True),
    sa.Column('redacteur_id', sa.Integer(), nullable=False),
    sa.Column('periode_debut', sa.Date(), nullable=False),
    sa.Column('periode_fin', sa.Date(), nullable=False),
    sa.Column('participants', sa.Text(), nullable=True),
    sa.Column('donnees_entree', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_revue_direction_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_revue_direction_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['redacteur_id'], ['utilisateur.id'], name=op.f('fk_revue_direction_redacteur_id_utilisateur')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revue_direction'))
    )
    op.create_table('seance',
    sa.Column('theme', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lieu', sa.String(length=120), nullable=False),
    sa.Column('animateur_id', sa.Integer(), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('planifiee', 'realisee', 'annulee', name='statut_seance'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animateur_id'], ['utilisateur.id'], name=op.f('fk_seance_animateur_id_utilisateur')),
    sa.ForeignKeyConstraint(['competence_id'], ['competence.id'], name=op.f('fk_seance_competence_id_competence')),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_seance_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_seance_modifie_par_id_utilisateur'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seance'))
    )
    op.create_table('cotation_audit',
    sa.Column('campagne_id', sa.Integer(), nullable=False),
    sa.Column('exigence_id', sa.Integer(), nullable=False),
    sa.Column('cotation', sa.Integer(), nullable=False),
    sa.Column('constat', sa.Text(), nullable=True),
    sa.Column('ecart', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('cotation BETWEEN 0 AND 2', name=op.f('ck_cotation_audit_cotation_0_2')),
    sa.ForeignKeyConstraint(['campagne_id'], ['campagne_audit.id'], name=op.f('fk_cotation_audit_campagne_id_campagne_audit')),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_cotation_audit_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['exigence_id'], ['exigence_audit.id'], name=op.f('fk_cotation_audit_exigence_id_exigence_audit')),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_cotation_audit_modifie_par_id_utilisateur'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cotation_audit'))
    )
    op.create_table('decision_revue',
    sa.Column('revue_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.Text(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('echeance', sa.Date(), nullable=False),
    sa.Column('statut', sa.Enum('ouverte', 'soldee', name='statut_decision_revue'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_decision_revue_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_decision_revue_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['responsable_id'], ['utilisateur.id'], name=op.f('fk_decision_revue_responsable_id_utilisateur')),
    sa.ForeignKeyConstraint(['revue_id'], ['revue_direction.id'], name=op.f('fk_decision_revue_revue_id_revue_direction')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_revue'))
    )
    op.create_table('emargement',
    sa.Column('seance_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('signe_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_emargement_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_emargement_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['participant_id'], ['utilisateur.id'], name=op.f('fk_emargement_participant_id_utilisateur')),
    sa.ForeignKeyConstraint(['seance_id'], ['seance.id'], name=op.f('fk_emargement_seance_id_seance')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emargement'))
    )
    op.create_table('tentative_quiz',
    sa.Column('seance_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('reponses', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('reussi', sa.Boolean(), nullable=False),
    sa.Column('date_passation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_tentative_quiz_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_tentative_quiz_modifie_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['participant_id'], ['utilisateur.id'], name=op.f('fk_tentative_quiz_participant_id_utilisateur')),
    sa.ForeignKeyConstraint(['seance_id'], ['seance.id'], name=op.f('fk_tentative_quiz_seance_id_seance')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tentative_quiz'))
    )
    # batch_alter_table : SQLite ne supporte pas l'ajout d'une contrainte de clé
    # étrangère nommée via ALTER TABLE (même motif que 14382e24e575).
    with op.batch_alter_table("action") as batch_op:
        batch_op.add_column(sa.Column('cotation_audit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            op.f('fk_action_cotation_audit_id_cotation_audit'), 'cotation_audit', ['cotation_audit_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("action") as batch_op:
        batch_op.drop_constraint(op.f('fk_action_cotation_audit_id_cotation_audit'), type_='foreignkey')
        batch_op.drop_column('cotation_audit_id')
    op.drop_table('tentative_quiz')
    op.drop_table('emargement')
    op.drop_table('decision_revue')
    op.drop_table('cotation_audit')
    op.drop_table('seance')
    op.drop_table('revue_direction')
    op.drop_table('habilitation')
    op.drop_table('campagne_audit')
    op.drop_table('question_quiz')
    op.drop_table('exigence_audit')
    op.drop_table('competence')
    # ### end Alembic commands ###
