"""pre-redaction des rapports (commentaire revue et audit)

Revision ID: f4181e7fcfe3
Revises: 9e17f86aa447
Create Date: 2026-09-07 03:38:02.424969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4181e7fcfe3'
down_revision: Union[str, Sequence[str], None] = '9e17f86aa447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust ###
    # `server_default` ajouté à la main (absent de l'autogénération) : une
    # colonne NOT NULL ajoutée à une table déjà peuplée exige une valeur par
    # défaut au niveau SQL, sans quoi SQLite (et PostgreSQL) refuse l'ajout —
    # `default=False` sur le modèle (app/db/base.py) ne s'applique qu'aux
    # nouvelles lignes insérées via l'ORM, jamais aux lignes déjà en base.
    op.add_column('campagne_audit', sa.Column('commentaire_ia', sa.Text(), nullable=True))
    op.add_column('campagne_audit', sa.Column('commentaire_valide', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('revue_direction', sa.Column('commentaire_ia', sa.Text(), nullable=True))
    op.add_column('revue_direction', sa.Column('commentaire_valide', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revue_direction', 'commentaire_valide')
    op.drop_column('revue_direction', 'commentaire_ia')
    op.drop_column('campagne_audit', 'commentaire_valide')
    op.drop_column('campagne_audit', 'commentaire_ia')
    # ### end Alembic commands ###
