"""ajout point_checklist et retrait taux_conformite stocke

Revision ID: fb8c539876c8
Revises: 4b398dde2947
Create Date: 2026-09-06 04:31:53.830996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb8c539876c8'
down_revision: Union[str, Sequence[str], None] = '4b398dde2947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_checklist',
    sa.Column('type_inspection', sa.Enum('locaux', 'incendie', 'electricite', 'installations', 'equipements', name='type_inspection_point'), nullable=False),
    sa.Column('categorie', sa.String(length=120), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=300), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], name=op.f('fk_point_checklist_cree_par_id_utilisateur'), use_alter=True),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], name=op.f('fk_point_checklist_modifie_par_id_utilisateur'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_point_checklist'))
    )
    # batch_alter_table par cohérence avec les autres migrations (voir
    # 4b398dde2947) même si le SQLite embarqué ici supporte DROP COLUMN
    # directement depuis la 3.35 — ne pas dépendre de la version du moteur.
    with op.batch_alter_table("inspection") as batch_op:
        batch_op.drop_column("taux_conformite")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inspection") as batch_op:
        batch_op.add_column(sa.Column("taux_conformite", sa.NUMERIC(precision=5, scale=2), nullable=True))
    op.drop_table('point_checklist')
    # ### end Alembic commands ###
